<a href="https://colab.research.google.com/github/manalibhoir22/manali/blob/master/data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
products = pd.read_excel('data.xlsx')
products.head()

   Unnamed: 0      reviewerID  ... unixReviewTime   reviewTime
0           1  A30TL5EWN6DFXT  ...     1400630400  05 21, 2014
1           2   ASY55RVNIL0UD  ...     1389657600  01 14, 2014
2           3  A2TMXE2AFO7ONB  ...     1403740800  06 26, 2014
3           4   AWJ0WZQYMYFQ4  ...     1382313600  10 21, 2013
4           5   ATX7CZYFXI1KW  ...     1359849600   02 3, 2013

[5 rows x 10 columns]

In [3]:
def sentiment(n):
    return 1 if n >= 4 else 0
products['sentiment'] = products['overall'].apply(sentiment)
products.head()

   Unnamed: 0      reviewerID  ...   reviewTime sentiment
0           1  A30TL5EWN6DFXT  ...  05 21, 2014         1
1           2   ASY55RVNIL0UD  ...  01 14, 2014         1
2           3  A2TMXE2AFO7ONB  ...  06 26, 2014         1
3           4   AWJ0WZQYMYFQ4  ...  10 21, 2013         1
4           5   ATX7CZYFXI1KW  ...   02 3, 2013         1

[5 rows x 11 columns]

In [5]:
products.drop(products.columns[[0,1,3,4,7,8]],axis=1,inplace=True)
products.head()

         asin  ... sentiment
0  120401325X  ...         1
1  120401325X  ...         1
2  120401325X  ...         1
3  120401325X  ...         1
4  120401325X  ...         1

[5 rows x 5 columns]